- name: jkh uat system
  hosts: rl-n1
  become: true
  become_user: ecp
  tasks:
  - name: Clean Workspace
    ansible.builtin.file:
      path: home/ecp/ws19
      state: absent
      mode: ''
  - name: Create a new workspace
    ansible.builtin.file:
      path: home/ecp/ws19
      state: directory
      mode: 0755
  - name: Download Artifacts
    get_url:
      url: http://159.223.54.208:9000/ecp-core/artifacts.zip
      dest: home/ecp/ws19/downloaded_file.zip
  - name: Extract artifacts
    command: unzip home/ecp/ws19/downloaded_file.zip -d home/ecp/ws19/downloaded_file
  - name: Create Dockerfile
    template:
      src: /Users/admin/Documents/Personal/ECPMasterNode/ECPMaster/ContainedSystemTemplate/Dockerfile
      dest: home/ecp/ws19/downloaded_file/Dockerfile
  - name: Ensure docker is running
    service:
      name: docker
      state: started
  - name: Docker login
    docker_login:
      username: sandevdewthilina2000@gmail.com
      password: sandevdsic123
  - name: Build and push docker image
    community.docker.docker_image:
      build:
        path: home/ecp/ws19/downloaded_file
      name: sandevdewthilina/ecp-core
      tag: d19-a1-atv3
      push: true
      source: build
  - name: Create DB
    command: docker exec -i mysql-core mysql -u root --password=r00t1@88Hetz2022 -e "CREATE DATABASE IF NOT EXISTS cherish_v3"
  - name: Copy backup to mysql docker
    command: docker cp home/ecp/ws19/downloaded_file/artifacts/goldencopy_v2_20240216_164002.sql mysql-core:/tmp/goldencopy_v2_20240216_164002.sql
  - name: Restore Database
    command: docker exec -i mysql-core mysql -u root --password=r00t1@88Hetz2022 -e "use cherish_v3; source /tmp/goldencopy_v2_20240216_164002.sql"
    ignore_errors: yes
  - name: Run Web Docker Container
    docker_container:
      name: deployment-19
      image: sandevdewthilina/ecp-core:d19-a1-atv3
      state: started
      restart_policy: no
      ports:
      - 18001:6555
      volumes: 
      etc_hosts:
        localhost: host-gateway
  - name: Clean workspace
    ansible.builtin.file:
      path: home/ecp/ws19
      state: absent
      mode: ''
