- name: Deploy docker container
  hosts: rl
  become: true
  become_user: ecp
  tasks:
    - name: Ensure docker is running
      service:
        name: docker
        state: started
        
    - name: Deploy Docker container
      docker_container:
        name: mysql-core
        image: mysql:8.3.0
        # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
        # (this is just an example, not intended to be a production configuration)
        command: ["--default-authentication-plugin=mysql_native_password"]
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: r00t1@88Hetz2022
          MYSQL_DATABASE: cherish_v3
        ports:
          - "3306:3306"
        volumes:
          - ./mysql-volume:/var/lib/mysql