version: '3.1'

services:
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped