version: '3.1'
services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t1@88Hetz2022
      MYSQL_DATABASE: cherish_v3
    ports:
      - 3306:3306
  
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080